services:
    tom_atom.twig.atom_extension:
        class: TomAtom\AtomBundle\Twig\TomAtomExtension
        tags:
            - { name: twig.extension } 
        arguments:
            - "@doctrine.orm.entity_manager"  
            - "@security.authorization_checker"
            - "@kernel"
